// Generated by AgentCode Blueprint — do not edit directly.
// Source: .agentcode/blueprints/labels.yaml
import { z } from 'zod';
import type { ModelRegistration } from '@agentcode-dev/agentcode-nestjs';

import { LabelPolicy } from '../policies/LabelPolicy';

// ---------------------------------------------------------------------------
// Validation schemas per role
// ---------------------------------------------------------------------------

const validationStore: Record<string, z.ZodTypeAny> = {
  owner: z.object({
    name: z.string().optional(),
    color: z.string().optional(),
  }),
  admin: z.object({
    name: z.string().optional(),
    color: z.string().optional(),
  }),
  manager: z.object({
    name: z.string().optional(),
    color: z.string().optional(),
  }),
  member: z.object({}),
  viewer: z.object({}),
};

const validationUpdate: Record<string, z.ZodTypeAny> = {
  owner: z.object({
    name: z.string().optional(),
    color: z.string().optional(),
  }),
  admin: z.object({
    name: z.string().optional(),
    color: z.string().optional(),
  }),
  manager: z.object({
    name: z.string().optional(),
    color: z.string().optional(),
  }),
  member: z.object({}),
  viewer: z.object({}),
};

// ---------------------------------------------------------------------------
// ModelRegistration
// ---------------------------------------------------------------------------

export const labelsRegistration: ModelRegistration = {
  model: 'Label',
  policy: LabelPolicy,
  validationStore,
  validationUpdate,
  allowedFilters: ["name"],
  allowedSorts: ["name"],
  allowedSearch: ["name"],
  belongsToOrganization: true,
  softDeletes: true,
  hasAuditTrail: false,
};
