// Generated by AgentCode Blueprint — do not edit directly.
// Source: .agentcode/blueprints/projects.yaml
import { z } from 'zod';
import type { ModelRegistration } from '@agentcode-dev/agentcode-nestjs';

import { ProjectPolicy } from '../policies/ProjectPolicy';

// ---------------------------------------------------------------------------
// Validation schemas per role
// ---------------------------------------------------------------------------

const validationStore: Record<string, z.ZodTypeAny> = {
  owner: z.object({
    title: z.string(),
    description: z.string().nullable().optional(),
    status: z.string(),
    budget: z.number().nullable().optional(),
    internalNotes: z.string().nullable().optional(),
    startsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
    endsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
  }),
  admin: z.object({
    title: z.string(),
    description: z.string().nullable().optional(),
    status: z.string(),
    budget: z.number().nullable().optional(),
    internalNotes: z.string().nullable().optional(),
    startsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
    endsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
  }),
  manager: z.object({
    title: z.string(),
    description: z.string().nullable().optional(),
    status: z.string(),
    startsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
    endsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
  }),
  member: z.object({}),
  viewer: z.object({}),
};

const validationUpdate: Record<string, z.ZodTypeAny> = {
  owner: z.object({
    title: z.string().optional(),
    description: z.string().nullable().optional(),
    status: z.string().optional(),
    budget: z.number().nullable().optional(),
    internalNotes: z.string().nullable().optional(),
    startsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
    endsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
  }),
  admin: z.object({
    title: z.string().optional(),
    description: z.string().nullable().optional(),
    status: z.string().optional(),
    budget: z.number().nullable().optional(),
    internalNotes: z.string().nullable().optional(),
    startsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
    endsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
  }),
  manager: z.object({
    title: z.string().optional(),
    description: z.string().nullable().optional(),
    status: z.string().optional(),
    startsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
    endsAt: z.string().datetime({ offset: true }).or(z.date()).nullable().optional(),
  }),
  member: z.object({}),
  viewer: z.object({}),
};

// ---------------------------------------------------------------------------
// ModelRegistration
// ---------------------------------------------------------------------------

export const projectsRegistration: ModelRegistration = {
  model: 'Project',
  policy: ProjectPolicy,
  validationStore,
  validationUpdate,
  allowedFilters: ["title","status"],
  allowedSorts: ["title","status","startsAt","endsAt"],
  allowedSearch: ["title"],
  belongsToOrganization: true,
  softDeletes: true,
  hasAuditTrail: true,
};
