// Generated by AgentCode Blueprint — do not edit directly.
// Source: .agentcode/blueprints/tasks.yaml
import { z } from 'zod';
import type { ModelRegistration } from '@agentcode-dev/agentcode-nestjs';

import { TaskPolicy } from '../policies/TaskPolicy';

// ---------------------------------------------------------------------------
// Validation schemas per role
// ---------------------------------------------------------------------------

const validationStore: Record<string, z.ZodTypeAny> = {
  owner: z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    status: z.string().optional(),
    priority: z.string().optional(),
    estimatedHours: z.number().optional(),
    dueDate: z.string().datetime({ offset: true }).or(z.date()).optional(),
    projectId: z.number().int().optional(),
    assignedTo: z.number().int().optional(),
  }),
  admin: z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    status: z.string().optional(),
    priority: z.string().optional(),
    estimatedHours: z.number().optional(),
    dueDate: z.string().datetime({ offset: true }).or(z.date()).optional(),
    projectId: z.number().int().optional(),
    assignedTo: z.number().int().optional(),
  }),
  manager: z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    status: z.string().optional(),
    priority: z.string().optional(),
    estimatedHours: z.number().optional(),
    dueDate: z.string().datetime({ offset: true }).or(z.date()).optional(),
    projectId: z.number().int().optional(),
    assignedTo: z.number().int().optional(),
  }),
  member: z.object({}),
  viewer: z.object({}),
};

const validationUpdate: Record<string, z.ZodTypeAny> = {
  owner: z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    status: z.string().optional(),
    priority: z.string().optional(),
    estimatedHours: z.number().optional(),
    dueDate: z.string().datetime({ offset: true }).or(z.date()).optional(),
    projectId: z.number().int().optional(),
    assignedTo: z.number().int().optional(),
  }),
  admin: z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    status: z.string().optional(),
    priority: z.string().optional(),
    estimatedHours: z.number().optional(),
    dueDate: z.string().datetime({ offset: true }).or(z.date()).optional(),
    projectId: z.number().int().optional(),
    assignedTo: z.number().int().optional(),
  }),
  manager: z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    status: z.string().optional(),
    priority: z.string().optional(),
    estimatedHours: z.number().optional(),
    dueDate: z.string().datetime({ offset: true }).or(z.date()).optional(),
    projectId: z.number().int().optional(),
    assignedTo: z.number().int().optional(),
  }),
  member: z.object({
    status: z.string().optional(),
    description: z.string().optional(),
  }),
  viewer: z.object({}),
};

// ---------------------------------------------------------------------------
// ModelRegistration
// ---------------------------------------------------------------------------

export const tasksRegistration: ModelRegistration = {
  model: 'Task',
  policy: TaskPolicy,
  validationStore,
  validationUpdate,
  allowedFilters: ["title","status","priority"],
  allowedSorts: ["title","status","priority","dueDate"],
  allowedSearch: ["title"],
  belongsToOrganization: false,
  softDeletes: true,
  hasAuditTrail: true,
};
