// Generated by AgentCode Blueprint — do not edit directly.
// Source: .agentcode/blueprints/comments.yaml
import { ResourcePolicy } from '@agentcode-dev/agentcode-nestjs';

/**
 * Authorization policy for the Comment resource.
 * Regenerate with: npx agentcode blueprint
 */
export class CommentPolicy extends ResourcePolicy {
  override resourceSlug = 'comments';

  override permittedAttributesForShow(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org) ||
      this.hasRole(user, 'member', org) ||
      this.hasRole(user, 'viewer', org)) {
      return ['*'];
    }
    return [];
  }

  override hiddenAttributesForShow(user: any, org?: any): string[] {
    return [];
  }

  override permittedAttributesForCreate(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org) ||
      this.hasRole(user, 'member', org)) {
      return ['body', 'taskId'];
    }
    return [];
  }

  override permittedAttributesForUpdate(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org) ||
      this.hasRole(user, 'member', org)) {
      return ['body'];
    }
    return [];
  }
}
