// Generated by AgentCode Blueprint — do not edit directly.
// Source: .agentcode/blueprints/labels.yaml
import { ActiveRolePolicy as ResourcePolicy } from './ActiveRolePolicy';

/**
 * Authorization policy for the Label resource.
 * Regenerate with: npx agentcode blueprint
 */
export class LabelPolicy extends ResourcePolicy {
  override resourceSlug = 'labels';

  override permittedAttributesForShow(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org) ||
      this.hasRole(user, 'member', org) ||
      this.hasRole(user, 'viewer', org)) {
      return ['*'];
    }
    return [];
  }

  override hiddenAttributesForShow(user: any, org?: any): string[] {
    return [];
  }

  override permittedAttributesForCreate(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org)) {
      return ['name', 'color'];
    }
    return [];
  }

  override permittedAttributesForUpdate(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org)) {
      return ['name', 'color'];
    }
    return [];
  }
}
