<?php

namespace App\Policies;

use App\Models\Label;
use AgentCode\Policies\ResourcePolicy;
use Illuminate\Contracts\Auth\Authenticatable;

/**
 * Policy for the Label resource.
 *
 * Generated by AgentCode Blueprint — zero-token deterministic generation.
 * To regenerate, modify the blueprint YAML and run: php artisan agentcode:blueprint
 */
class LabelPolicy extends ResourcePolicy
{
    // ---------------------------------------------------------------
    // Attribute Permissions (generated from blueprint)
    // ---------------------------------------------------------------

    public function permittedAttributesForShow(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner')
            || $this->hasRole($user, 'admin')
            || $this->hasRole($user, 'manager')
            || $this->hasRole($user, 'member')
            || $this->hasRole($user, 'viewer')) {
            return ['*'];
        }

        return [];
    }

    public function hiddenAttributesForShow(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        return [];
    }

    public function permittedAttributesForCreate(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner')
            || $this->hasRole($user, 'admin')
            || $this->hasRole($user, 'manager')) {
            return ['name', 'color'];
        }

        return [];
    }

    public function permittedAttributesForUpdate(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner')
            || $this->hasRole($user, 'admin')
            || $this->hasRole($user, 'manager')) {
            return ['name', 'color'];
        }

        return [];
    }
}
