// Generated by AgentCode Blueprint — do not edit directly.
// Source: .agentcode/blueprints/comments.yaml
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Seed sample Comment rows.
 * Run: npx ts-node src/seeders/CommentSeeder.ts
 */
export async function seed(): Promise<void> {
  console.log('Seeding Comment...');

  await prisma.comment.upsert({
    where: { id: 1 },
    update: {},
    create: {
      id: 1,
      body: "Sample Body content for row 1.",
      taskId: 1,
      userId: 1,
    },
  });

  await prisma.comment.upsert({
    where: { id: 2 },
    update: {},
    create: {
      id: 2,
      body: "Sample Body content for row 2.",
      taskId: 1,
      userId: 1,
    },
  });

  await prisma.comment.upsert({
    where: { id: 3 },
    update: {},
    create: {
      id: 3,
      body: "Sample Body content for row 3.",
      taskId: 1,
      userId: 1,
    },
  });

  console.log('✓ Comment seeded (3 rows)');
}

// Allow running directly
if (require.main === module) {
  seed()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
}
